version: '3.1'

services:

  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 9002:80

       
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      -  9001:80
    environment:
      - PMA_ARBITRARY=1